#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# Generate
# ------------------------------------------------------------------------------
# object code (.o) from assemble code (.s)
# ------------------------------------------------------------------------------
as -o hello.o hello.s
# https://zestedesavoir.com/articles/130/programmez-en-langage-dassemblage-sous-linux/
# nasm
