#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# readelf (1)          - Displays information about ELF files.
# ------------------------------------------------------------------------------
#gcc -c hello.c
readelf -s hello.o
#readelf -a hello.o
