#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# gdb
# ------------------------------------------------------------------------------
# - needs special symbols
# - option: -g or else -ggdb
# ------------------------------------------------------------------------------
#gcc -Werror -ggdb -o stuff stuff.c stuff_tool.c
gcc -Werror -ggdb -o tuntap tuntap.c 
