#!/usr/bin/env bash
set -x
# ==============================================================================
# Scenario
# ------------------------------------------------------------------------------
# - object files .o
# - static lib .a
# - executable file 
#   - .a code (object code) is within this executable file
#   - .a modified => compilation needed !! <= be careful updates !!
# ==============================================================================
# compilation
gcc -c operation.c # generates operation.o
# ------------------------------------------------------------------------------
# static lib command
ar -q liboperation.a operation.o  # generates liboperation.a
# ------------------------------------------------------------------------------
nm operation.o # show symbols {T: defined, U:undefined}
nm liboperation.a # idem, show table symbols
# ------------------------------------------------------------------------------
file liboperation.a 
# ------------------------------------------------------------------------------
# compile and link (statically liboperation.a)
gcc -o main.exe main.c liboperation.a 
# ------------------------------------------------------------------------------
# run
./main.exe 
./main.exe 7 2
# ------------------------------------------------------------------------------
# Examine an executable and display a list of the shared librairies needed
ldd main.exe # list dynamic link (ldd) libraries
# ------------------------------------------------------------------------------
